version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: npm
    directory: /packages/types
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /packages/server
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /packages/react
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
